name: Deploy Larris Dark Mode Staging

on:
  push:
    branches:
      - Staging

jobs:
  deploy:
    name: Deploy to Staging Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 📂 Sync Files to Staging
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.STAGING_SERVER }}
          remote-user: ${{ secrets.STAGING_USER }}
          private-ssh-key: ${{ secrets.STAGING_SSH_KEY }}
          ssh-port: ${{ secrets.STAGING_SSH_PORT }}
          destination-path: ${{ secrets.STAGING_SITE_PATH }}
