name: Deploy Larris Dark Mode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: lint  # ensure lint job passes first

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ${{ secrets.TARGET_SERVER }}
        remote-user: ${{ secrets.REMOTE_USER }}
        private-ssh-key: ${{ secrets.SSH_KEY }}
        ssh-port: ${{ secrets.SSH_PORT }}
        destination-path: ${{ secrets.STAGING_SITE_PATH }}
        
        
        
        

